#!/bin/sh

#
# Start the LCDd service ...
#

case "$1" in
  start)
	printf "Starting LCDd: "
	LCDd &
        pidof LCDd
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping LCDd: "
	killall LCDd
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

