#!/bin/sh

#
# Start the lcdproc service ...
#

case "$1" in
  start)
	printf "Starting lcdproc: "
	lcdproc &
        pidof lcdproc
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	printf "Stopping LCDd: "
	killall lcdproc
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

