#!/bin/sh

CAL=$(cat /etc/ical.conf)

case "$1" in
	start)
		export TZ=GMT-1
		mkdir -p /var/spool/cron/crontabs
                if wget -q --no-check-certificate $CAL -O /tmp/icalendar.ical; then
		  ( echo "*/5	*	*	*	*	/etc/init.d/S91Cal restart" ; ical2crontab -i /tmp/icalendar.ical ) | crontab - 
		else
		  /etc/init.d/S40network restart
		fi
	        pid_mplayer=$(pidof mplayer)
		if [ -z "$pid_mplayer" ]; then
		        pid_lcd=$(pidof mplayer2LCDd.pl)
			if [ ! -z "$pid_lcd" ]; then
				kill $pid_lcd
			fi
		fi
		;;
	stop)
		echo "done."
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
		;;
esac

